# Repo: MySpace/TemplateRepo
# File: azure-pipeline2.yml
# just for fun added this

name: cicd_test

trigger:
  branches:
    include:
      - main

stages:
- stage: CI_Checks
  jobs:
  - job:
    displayName: Run the ARM script below
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo Hello World below script is to create storage account
      displayName: 'Creating Storage Account'
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure subscription 1(d335a5bd-1676-4e8e-ba9b-8565858d44ec)'
        subscriptionId: 'd335a5bd-1676-4e8e-ba9b-8565858d44ec'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Resourcegroup'
        location: 'East US 2'
        templateLocation: 'Linked artifact'
        csmFile: 'mystorage.json'
        deploymentMode: 'Incremental'
        overrideParameters: -storageAccountName sg09062023
